server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL:jdbc:sqlserver://localhost:14333;databaseName=db_auth;encrypt=false;trustServerCertificate=true}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:123}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET:MTIzNDU2NDU5OThEMzIxM0F6eGMzNTE2NTQzMjEzMjE2NTQ5OHEzMTNhMnMxZDMyMnp4M2MyMQ==}
  expiration-ms: 360000000

app:
  frontend-url: ${APP_FRONTEND_URL:http://localhost:3000}
  mail-from: ${MAIL_FROM:noreply@bookstore.com}

services:
  user-url: ${SERVICES_USER_URL:http://localhost:8082}

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.bookstore.auth: DEBUG
